-- Crear tabla para tracking de almacenamiento por coach
-- Permite saber cuánto espacio usa cada coach y en qué conceptos (video, image, pdf)

CREATE TABLE IF NOT EXISTS storage_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  concept TEXT NOT NULL CHECK (concept IN ('video', 'image', 'pdf', 'other')),
  gb_usage DECIMAL(12, 6) NOT NULL DEFAULT 0,
  products JSONB DEFAULT '[]'::jsonb, -- Array de activity_ids que usan este storage
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(coach_id, concept)
);

-- Índice para búsquedas por coach
CREATE INDEX IF NOT EXISTS idx_storage_usage_coach_id ON storage_usage(coach_id);

-- Índice para búsquedas por concepto
CREATE INDEX IF NOT EXISTS idx_storage_usage_concept ON storage_usage(concept);

-- Comentarios para documentación
COMMENT ON TABLE storage_usage IS 'Tracking de almacenamiento de archivos por coach. Concept puede ser video, image, pdf u other.';
COMMENT ON COLUMN storage_usage.concept IS 'Tipo de contenido: video, image, pdf u other';
COMMENT ON COLUMN storage_usage.gb_usage IS 'Espacio usado en GB (con 3 decimales de precisión)';
COMMENT ON COLUMN storage_usage.products IS 'Array JSON con los IDs de actividades que usan este storage';

-- Habilitar RLS
ALTER TABLE storage_usage ENABLE ROW LEVEL SECURITY;

-- Policy: Coaches pueden ver su propio storage
DROP POLICY IF EXISTS "Coaches can view their own storage usage" ON storage_usage;
CREATE POLICY "Coaches can view their own storage usage" ON storage_usage
  FOR SELECT USING (coach_id = auth.uid());

-- Policy: System puede insertar/actualizar (para job automático o API)
DROP POLICY IF EXISTS "System can manage storage usage" ON storage_usage;
CREATE POLICY "System can manage storage usage" ON storage_usage
  FOR ALL USING (TRUE) WITH CHECK (TRUE);

-- Trigger para actualizar updated_at
CREATE OR REPLACE FUNCTION update_storage_usage_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_storage_usage_updated_at ON storage_usage;
CREATE TRIGGER trigger_update_storage_usage_updated_at
  BEFORE UPDATE ON storage_usage
  FOR EACH ROW
  EXECUTE FUNCTION update_storage_usage_updated_at();

