CREATE TABLE IF NOT EXISTS activity_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT REFERENCES public.activities_base(id) ON DELETE CASCADE,
  image_url TEXT,
  video_url TEXT,
  vimeo_id TEXT,
  pdf_url TEXT
);

ALTER TABLE activity_media ENABLE ROW LEVEL SECURITY;

-- Policies for activity_media
DROP POLICY IF EXISTS "Allow read access to all activity_media." ON activity_media;
CREATE POLICY "Allow read access to all activity_media." ON activity_media
  FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Coaches can manage their activity media." ON activity_media;
CREATE POLICY "Coaches can manage their activity media." ON activity_media
  FOR ALL USING (EXISTS (SELECT 1 FROM public.activities_base WHERE id = activity_id AND coach_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.activities_base WHERE id = activity_id AND coach_id = auth.uid()));

DROP POLICY IF EXISTS "Admins can manage all activity media." ON activity_media;
CREATE POLICY "Admins can manage all activity media." ON activity_media
  FOR ALL USING (auth.uid() IN (SELECT user_id FROM public.user_roles WHERE role = 'admin')) WITH CHECK (auth.uid() IN (SELECT user_id FROM public.user_roles WHERE role = 'admin'));
