-- Migration to create activities snapshots table
-- This table stores information about expired programs that the user can still view.

CREATE TABLE IF NOT EXISTS public.actividades_vencidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    activity_id BIGINT NOT NULL REFERENCES public.activities(id) ON DELETE CASCADE,
    enrollment_id BIGINT REFERENCES public.activity_enrollments(id) ON DELETE SET NULL,
    nombre_programa TEXT NOT NULL,
    coach_nombre TEXT,
    fecha_inicio DATE,
    fecha_final DATE,
    fecha_vencimiento DATE,
    progreso_porcentaje INTEGER DEFAULT 0,
    categoria TEXT DEFAULT 'fitness',
    tipo_producto TEXT, -- programa, taller, doc
    image_url TEXT,
    rating_coach INTEGER,
    rating_omnia INTEGER,
    feedback_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure columns exist if table was already created in a previous run
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='actividades_vencidas' AND column_name='tipo_producto') THEN
        ALTER TABLE public.actividades_vencidas ADD COLUMN tipo_producto TEXT;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='actividades_vencidas' AND column_name='fecha_final') THEN
        ALTER TABLE public.actividades_vencidas ADD COLUMN fecha_final DATE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='actividades_vencidas' AND column_name='image_url') THEN
        ALTER TABLE public.actividades_vencidas ADD COLUMN image_url TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='actividades_vencidas' AND column_name='rating_coach') THEN
        ALTER TABLE public.actividades_vencidas ADD COLUMN rating_coach INTEGER;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='actividades_vencidas' AND column_name='rating_omnia') THEN
        ALTER TABLE public.actividades_vencidas ADD COLUMN rating_omnia INTEGER;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='actividades_vencidas' AND column_name='feedback_text') THEN
        ALTER TABLE public.actividades_vencidas ADD COLUMN feedback_text TEXT;
    END IF;

    -- Add unique constraint if not present
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'actividades_vencidas_enrollment_id_key') THEN
        ALTER TABLE public.actividades_vencidas ADD CONSTRAINT actividades_vencidas_enrollment_id_key UNIQUE(enrollment_id);
    END IF;
END $$;

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_actividades_vencidas_client_id ON public.actividades_vencidas(client_id);
CREATE INDEX IF NOT EXISTS idx_actividades_vencidas_activity_id ON public.actividades_vencidas(activity_id);

-- RLS Policies
ALTER TABLE public.actividades_vencidas ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Clients can view their own expired activities" ON public.actividades_vencidas;
    DROP POLICY IF EXISTS "Clients can delete their own expired activities" ON public.actividades_vencidas;
END $$;

CREATE POLICY "Clients can view their own expired activities" 
ON public.actividades_vencidas FOR SELECT 
TO authenticated 
USING (auth.uid() = client_id);

CREATE POLICY "Clients can delete their own expired activities" 
ON public.actividades_vencidas FOR DELETE 
TO authenticated 
USING (auth.uid() = client_id);

-- One-time population of obviously expired activities
INSERT INTO public.actividades_vencidas (
    client_id,
    activity_id,
    enrollment_id,
    nombre_programa,
    coach_nombre,
    fecha_inicio,
    fecha_final,
    fecha_vencimiento,
    progreso_porcentaje,
    categoria,
    tipo_producto,
    image_url,
    rating_coach,
    rating_omnia,
    feedback_text
)
SELECT 
    ae.client_id,
    ae.activity_id,
    ae.id as enrollment_id,
    a.title as nombre_programa,
    u.full_name as coach_nombre,
    ae.start_date as fecha_inicio,
    ae.program_end_date as fecha_final,
    ae.expiration_date as fecha_vencimiento,
    (
        SELECT CASE 
            WHEN SUM(items_objetivo) > 0 
            THEN (SUM(items_completados) * 100 / SUM(items_objetivo))::INTEGER 
            ELSE 0 
        END
        FROM public.progreso_diario_actividad pda
        WHERE pda.enrollment_id = ae.id
    ) as progreso_porcentaje,
    a.categoria,
    COALESCE(a.type, a.categoria) as tipo_producto,
    (SELECT image_url FROM public.activity_media WHERE activity_id = a.id LIMIT 1) as image_url,
    surv.coach_method_rating as rating_coach,
    surv.calificacion_omnia as rating_omnia,
    surv.comments as feedback_text
FROM public.activity_enrollments ae
JOIN public.activities a ON ae.activity_id = a.id
LEFT JOIN public.user_profiles u ON a.coach_id = u.id
LEFT JOIN public.activity_surveys surv ON (surv.enrollment_id = ae.id)
WHERE ae.expiration_date < CURRENT_DATE
  AND NOT EXISTS (
    SELECT 1 FROM public.actividades_vencidas av 
    WHERE av.enrollment_id = ae.id
  )
ON CONFLICT (enrollment_id) DO UPDATE SET
    image_url = EXCLUDED.image_url,
    rating_coach = EXCLUDED.rating_coach,
    rating_omnia = EXCLUDED.rating_omnia,
    feedback_text = EXCLUDED.feedback_text;
